### ISSUE TITLE
Doesn't seem to register with client

### ISSUE THREAD

**Issue by uriel1998** [professorg/ChatPing#1]
The /chatping command gives me "unknown command" both SSP and SMP; any idea or way I could help debug
![2019-09-28--1569671728_1366x768_scrot](https://user-images.githubusercontent.com/1130750/65816090-83f21c80-e1c5-11e9-88bf-03fa43196ee2.png)
?  (Otherwise yes, this is exactly what I'm looking for).

**Comment by professorg** [comment]
Fixed with [this release](https://github.com/professorg/ChatPing/releases/tag/v1.0.1), I think. The problem was that the mod's dependencies (which I didn't list, oops) were not being included in the jar. They are now included.
