### ISSUE TITLE
Doesn't pick up chat in channels

### ISSUE THREAD

**Issue by uriel1998** [professorg/ChatPing#2]
It works beautifully in regular SSP chat.  Absolutely wonderful, and exactly what I wanted.

On the SMP server I play on, though, it's *not* working. The server uses channels - I'm not sure of which Spigot plugin it is - so that most chat is on channel [g] and staff chat is on channel [z] . For example, right after it worked in SSP, I logged on and did this:
![2019-09-29_16 07 37](https://user-images.githubusercontent.com/1130750/65838658-55626780-e2d3-11e9-881e-a879bc392baf.png)

And there were no dings or anything.

It's probably regex escaping, but since I don't know how to compile Java stuff, I can't fork around with it myself.  Any ideas or additional info that would be helpful in puzzling this out?

Thanks so much for your work and responsiveness!

**Comment by professorg** [comment]
I'm looking into it. If you do get a chance to find out what the plugin is, it would be really helpful. I'll be testing for a while, but I might not have much time as today is my first day of college. I have a feeling it has to do with styled text, but I'm still figuring it out.

**Comment by professorg** [comment]
Alright, the newest release v1.0.2 should fix this issue. @uriel1998 
Hope this works for you.

**Comment by uriel1998** [comment]
Works perfectly!  Thank you!
